server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://xxxxx.mysql.rds.aliyuncs.com:3306/xxxxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxxx
    password: xxxxx
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j,config
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4
    lettuce:
      pool:
        max-active: 50
        max-idle: 8
        min-idle: 0
    timeout: 30000ms

mq:
  accessKey: xxxxx
  secretKey: xxxxx
  nameSrvAddr: http://xxxxx.cn-shenzhen.mq.aliyuncs.com:80
  signName: xxxxx
  consumer:
    enable: true

ig:
  partnerKey: xxxxx
  publicKey: xxxxx
  secretKey: xxxxx
  apiUrl: https://www.openpla.com
  appId: 730
