package com.csgo.constants;

/**
 * @author admin
 */
public final class LuckyProductConstants {

    public static final String LUCKY_PRODUCT_PREFIX = "LUCKY_PRODUCT:";
    public static final String LUCKY_PRODUCT_IN_PROBABILITY = LUCKY_PRODUCT_PREFIX + "IN_PROBABILITY";
    public static final String LUCKY_PRODUCT_LUCKY_IN_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LUCKY_IN_PROBABILITY";
    public static final String LUCKY_PRODUCT_HIGH_EXPLOSIVE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "HIGH_EXPLOSIVE_PROBABILITY";

    public static final String LUCKY_PRODUCT_LEVEL1_POINT = LUCKY_PRODUCT_PREFIX + "LEVEL1_POINT";
    public static final String LUCKY_PRODUCT_LEVEL2_POINT = LUCKY_PRODUCT_PREFIX + "LEVEL2_POINT";
    public static final String LUCKY_PRODUCT_LEVEL3_POINT = LUCKY_PRODUCT_PREFIX + "LEVEL3_POINT";
    public static final String LUCKY_PRODUCT_LEVEL4_POINT = LUCKY_PRODUCT_PREFIX + "LEVEL4_POINT";

    public static final String LUCKY_PRODUCT_LEVEL1_MIN_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL1_MIN_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL1_MAX_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL1_MAX_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL2_MIN_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL2_MIN_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL2_MAX_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL2_MAX_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL3_MIN_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL3_MIN_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL3_MAX_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL3_MAX_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL4_MIN_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL4_MIN_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL4_MAX_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL4_MAX_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL5_MIN_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL5_MIN_INCREASE_PROBABILITY";
    public static final String LUCKY_PRODUCT_LEVEL5_MAX_INCREASE_PROBABILITY = LUCKY_PRODUCT_PREFIX + "LEVEL5_MAX_INCREASE_PROBABILITY";

    public static final String COMMISSION_RATE = LUCKY_PRODUCT_PREFIX + "COMMISSION_RATE";

    public static final String LUCKY_PRODUCT_USER_INIT_LUCKY_VALUE_MIN = LUCKY_PRODUCT_PREFIX + "USER_INIT_LUCKY_VALUE_MIN";
    public static final String LUCKY_PRODUCT_USER_INIT_LUCKY_VALUE_MAX = LUCKY_PRODUCT_PREFIX + "USER_INIT_LUCKY_VALUE_MAX";
}
